# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\qqq00\Documents\pyprojects\BASS-BEMS\BASS-BEMS\modules\modbus_comm\modbus_hunter\modbus_hunter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(742, 676)
        self.modbustable = QtWidgets.QTableWidget(Dialog)
        self.modbustable.setGeometry(QtCore.QRect(10, 110, 721, 501))
        self.modbustable.setFrameShape(QtWidgets.QFrame.Panel)
        self.modbustable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.modbustable.setShowGrid(True)
        self.modbustable.setCornerButtonEnabled(True)
        self.modbustable.setRowCount(0)
        self.modbustable.setObjectName("modbustable")
        self.modbustable.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.modbustable.setHorizontalHeaderItem(6, item)
        self.pollbtn = QtWidgets.QPushButton(Dialog)
        self.pollbtn.setGeometry(QtCore.QRect(10, 70, 361, 30))
        self.pollbtn.setObjectName("pollbtn")
        self.statuslabel = QtWidgets.QLabel(Dialog)
        self.statuslabel.setGeometry(QtCore.QRect(10, 21, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statuslabel.setFont(font)
        self.statuslabel.setObjectName("statuslabel")
        self.pollstopbtn = QtWidgets.QPushButton(Dialog)
        self.pollstopbtn.setGeometry(QtCore.QRect(380, 70, 351, 30))
        self.pollstopbtn.setObjectName("pollstopbtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.modbustable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Equip. Name"))
        item = self.modbustable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Equip. Address"))
        item = self.modbustable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Tag Name"))
        item = self.modbustable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Tag ID"))
        item = self.modbustable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Type"))
        item = self.modbustable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Modbus Address"))
        item = self.modbustable.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Value"))
        self.pollbtn.setText(_translate("Dialog", "조회시작"))
        self.statuslabel.setText(_translate("Dialog", "File -> Open TAGs(단축키 : 컨트롤+O) 에서 MODBUS 설정 파일을 먼저 로드하세요."))
        self.pollstopbtn.setText(_translate("Dialog", "조회중단"))
